name: Checks
on:
  pull_request:
    branches: [ main ]

jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHU_TOKEB: ${{ secrets.DOCKERHUB_TOKEN }}